### ISSUE TITLE
Cool blog post, mind if I link to it from the decaffeinate README?

### ISSUE THREAD

**Issue by alangpierce** [bugsnag/depercolator#2]
Hey @wordofchristian, I'm the main person working on decaffeinate these days, and cool to see a blog post about it. Seems like it would be useful to put on the decaffeinate README (or somewhere in the docs) as a real-world example. Mind if I add a link to it?

Also, a few random thoughts on the blog post:

> We don’t currently have a good solution around this, so sometimes it is preferable to convert the file on a different branch prior to any logic changes in order to have the conversion code reviewed separately.

Yep, that's what we do as well (at Benchling). We always have a few commits for just the automated changes (the ones generated by bulk-decaffeinate), then another commit for manual style fix-ups, then any functional changes happen in a separate review.

> In order to make this work we can use coffee-react-transform on the file to convert the JSX to plain coffeescript before piping it into decaffeinate

Makes plenty of sense to me! In my codebase we use React, but we don't use CJSX in CoffeeScript code, so it was a bit easier to run decaffeinate directly and then use create-element-to-jsx after that.

It's potentially possible that decaffeinate will support language extensions like CJSX and Iced CoffeeScript in the future, which would make this whole thing a lot easier, although probably not soon.

> Most of the work is already done, but this process alone often has problems with properly formatting large chunks of JSX, often placing it on one long unreadable line. To improve the formatting we can use a tool called prettier to reformat our JSX file.

Yep, I ran into that, too, and considered prettier, although I decided that prettier's output was too different from our normal style. Although maybe with `eslint --fix` after prettier it would actually look fine. I ended up fixing the JSX formatting issue instead ( https://github.com/reactjs/react-codemod/pull/95 ), and I'm reasonably happy with the overall formatting after that fix.

> `__guard__` works but is definitely not pretty (probably as a signal that it should be removed and rewritten). 

Yep, we always rewrite `__guard__` usages as part of cleaning up the file. For simple cases, decaffeinate can often generate better code, but in general it's hard to convert `?.` into code that is both nice-looking and 100% correct.

Also, it probably wouldn't be out of the question to hook up cjsx-transform and prettier to the [bulk-decaffeinate](https://github.com/decaffeinate/bulk-decaffeinate) project. Ideally that would be extensible enough to be generally useful, although I certainly understand that sometimes it's easiest to just write your own thing.

Anyway, thanks for the shout-out, and happy to see that you're finding decaffeinate useful. 😄

**Comment by wordofchristian** [comment]
😃  I'm glad you like the blog post. I think linking to it from the decaffeinate README would be a great idea. 

>I ended up fixing the JSX formatting issue instead ( reactjs/react-codemod#95 ), and I'm reasonably happy with the overall formatting after that fix.

Glad you got this fixed it removes the vast majority of the issues.

> Yep, we always rewrite __guard__ usages as part of cleaning up the file. For simple cases, decaffeinate can often generate better code, but in general it's hard to convert ?. into code that is both nice-looking and 100% correct.

Yeah it doesn't seem like there is a great way around this. The lodash [`_.get`](https://lodash.com/docs/4.17.4#get) kind of works but it can't call functions in the key path.
